# Generated by Django 4.0.6 on 2022-11-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0019_remove_attendancereportstaff_attendance_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_message',
            field=models.TextField(null=True),
        ),
    ]
